project:
  type: website
  output-dir: _site
  resources:
    - app.js
    - styles.css

website:
  title: "Static Quarto Application"

format:
  html:
    theme: none
    css: styles.css
    toc: false
