from __future__ import annotations

from pathlib import Path
import tempfile
import unittest

from repo_familiar.generator import GenerationOptions, generate_project


REPO_ROOT = Path(__file__).resolve().parents[1]
EXAMPLE_ROOT = REPO_ROOT / "examples/basic-agentic-project"
PYTHON_EXAMPLE_ROOT = REPO_ROOT / "examples/python-reproducible-project"
STATIC_APP_EXAMPLE_ROOT = REPO_ROOT / "examples/static-quarto-application"


class ExampleSnapshotTests(unittest.TestCase):
    def test_basic_example_matches_generator_output(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "basic-agentic-project"
            generate_project(
                GenerationOptions(
                    name="Basic Agentic Project",
                    description="Example downstream repository generated by repo-familiar.",
                    output_dir=output_dir,
                    template="basic",
                    agent_harnesses=("opencode", "paseo", "hermes"),
                    model_profiles=("default-coding", "budget-review"),
                    reference_type="git",
                    reference_url="https://example.invalid/repo-familiar.git",
                    reference_ref="example-snapshot",
                    generated_at="2026-05-10T00:00:00Z",
                )
            )

            self._assert_snapshot(output_dir, EXAMPLE_ROOT)

    def test_python_reproducible_example_matches_generator_output(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "python-reproducible-project"
            generate_project(
                GenerationOptions(
                    name="Python Reproducible Project",
                    description="Executable reproducible data science project generated by repo-familiar.",
                    output_dir=output_dir,
                    template="python-reproducible",
                    generated_at="2026-08-10T00:00:00Z",
                )
            )

            self._assert_snapshot(output_dir, PYTHON_EXAMPLE_ROOT)

    def test_static_quarto_application_example_matches_generator_output(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "static-quarto-application"
            generate_project(
                GenerationOptions(
                    name="Static Quarto Application",
                    description="Static Quarto client with a FastAPI request boundary generated by repo-familiar.",
                    output_dir=output_dir,
                    template="static-quarto-application",
                    generated_at="2026-08-10T00:00:00Z",
                )
            )

            self._assert_snapshot(output_dir, STATIC_APP_EXAMPLE_ROOT)

    def test_new_examples_encode_executable_evidence(self) -> None:
        python_agents = (PYTHON_EXAMPLE_ROOT / "AGENTS.md").read_text()
        static_agents = (STATIC_APP_EXAMPLE_ROOT / "AGENTS.md").read_text()
        static_client = (STATIC_APP_EXAMPLE_ROOT / "app/app.js").read_text()
        python_manifest = (PYTHON_EXAMPLE_ROOT / "pyproject.toml").read_text()
        static_manifest = (STATIC_APP_EXAMPLE_ROOT / "pyproject.toml").read_text()
        static_workflow = (
            STATIC_APP_EXAMPLE_ROOT / ".github/workflows/ci.yml"
        ).read_text()

        self.assertIn("uv run reproduce --check", python_agents)
        self.assertIn("Documentation As Evidence", python_agents)
        self.assertIn("browser code initiates", static_agents)
        self.assertIn('fetch("/api/v1/analyze"', static_client)
        self.assertNotIn("fastapi", python_manifest.lower())
        self.assertNotIn("playwright", python_manifest.lower())
        self.assertIn("fastapi", static_manifest.lower())
        self.assertIn("httpx2", static_manifest.lower())
        self.assertIn("pytest -m browser", static_workflow)

    def test_basic_example_agent_instructions_include_engineering_defaults(self) -> None:
        agents = (EXAMPLE_ROOT / "AGENTS.md").read_text()

        self.assertIn("## Engineering Defaults", agents)
        self.assertIn("## Documentation Defaults", agents)
        self.assertIn("Divio documentation system", agents)
        self.assertIn("Use red/green TDD", agents)
        self.assertIn("real browser flow", agents)
        self.assertIn("screen readers", agents)
        self.assertIn("Universal Design for Learning", agents)
        self.assertIn("right-to-left language support", agents)

    def _assert_snapshot(self, output_dir: Path, expected_root: Path) -> None:
        expected_files = sorted(
            path.relative_to(expected_root).as_posix()
            for path in expected_root.rglob("*")
            if path.is_file()
        )
        actual_files = sorted(
            path.relative_to(output_dir).as_posix()
            for path in output_dir.rglob("*")
            if path.is_file()
        )

        self.assertEqual(actual_files, expected_files)
        for relative_path in expected_files:
            self.assertEqual(
                (output_dir / relative_path).read_text(),
                (expected_root / relative_path).read_text(),
                relative_path,
            )


if __name__ == "__main__":
    unittest.main()
