from __future__ import annotations

from pathlib import Path
import tempfile
import unittest

from repo_familiar.generator import GenerationOptions, generate_project


REPO_ROOT = Path(__file__).resolve().parents[1]
EXAMPLE_ROOT = REPO_ROOT / "examples/basic-agentic-project"


class ExampleSnapshotTests(unittest.TestCase):
    def test_basic_example_matches_generator_output(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "basic-agentic-project"
            generate_project(
                GenerationOptions(
                    name="Basic Agentic Project",
                    description="Example downstream repository generated by repo-familiar.",
                    output_dir=output_dir,
                    agent_harnesses=("opencode", "paseo", "hermes"),
                    model_profiles=("default-coding", "budget-review"),
                    reference_type="git",
                    reference_url="https://example.invalid/repo-familiar.git",
                    reference_ref="example-snapshot",
                    generated_at="2026-05-10T00:00:00Z",
                )
            )

            expected_files = sorted(
                path.relative_to(EXAMPLE_ROOT).as_posix()
                for path in EXAMPLE_ROOT.rglob("*")
                if path.is_file()
            )
            actual_files = sorted(
                path.relative_to(output_dir).as_posix()
                for path in output_dir.rglob("*")
                if path.is_file()
            )

            self.assertEqual(actual_files, expected_files)
            for relative_path in expected_files:
                self.assertEqual(
                    (output_dir / relative_path).read_text(),
                    (EXAMPLE_ROOT / relative_path).read_text(),
                    relative_path,
                )

    def test_basic_example_agent_instructions_include_engineering_defaults(self) -> None:
        agents = (EXAMPLE_ROOT / "AGENTS.md").read_text()

        self.assertIn("## Engineering Defaults", agents)
        self.assertIn("Use red/green TDD", agents)
        self.assertIn("real browser flow", agents)
        self.assertIn("screen readers", agents)
        self.assertIn("Universal Design for Learning", agents)
        self.assertIn("right-to-left language support", agents)


if __name__ == "__main__":
    unittest.main()
